name: KeepExperience
main: octopush\experience\KeepExperience
version: 1.0-alpha
api: 4.0.1
author: Octopush

permissions:
  keepexperience.cmd:
    description: "Main permission for KeepExperience command"
    default: op

commands:
  keepxp:
    description: "Main command for KeepExperience plugin"
    permission: keepexperience.cmd